version: '2.4'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - nginx-reverse-proxy 
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: "abdennour@abbi-studio.fr"
    networks: 
      - nginx-reverse-proxy 

volumes:
  conf: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './conf.d'
  html: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './html'
  vhost: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './vhost.d'
  dhparam: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './dhparam'
  certs: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './certs'

networks:
  nginx-reverse-proxy:
    name: nginx-reverse-proxy
