version: '3.5'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - nginx-reverse-proxy 
networks:
  nginx-reverse-proxy:
    name: nginx-reverse-proxy
